//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDICOMExample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST_SCU")]
        public string SCU_aet {
            get {
                return ((string)(this["SCU_aet"]));
            }
            set {
                this["SCU_aet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2104")]
        public string SCU_port {
            get {
                return ((string)(this["SCU_port"]));
            }
            set {
                this["SCU_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SCU_use_tls {
            get {
                return ((bool)(this["SCU_use_tls"]));
            }
            set {
                this["SCU_use_tls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SCU_cert_cn {
            get {
                return ((string)(this["SCU_cert_cn"]));
            }
            set {
                this["SCU_cert_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SCU_thumbprint {
            get {
                return ((string)(this["SCU_thumbprint"]));
            }
            set {
                this["SCU_thumbprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SCU_accepted {
            get {
                return ((string)(this["SCU_accepted"]));
            }
            set {
                this["SCU_accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST_PACS")]
        public string RSCP_aet {
            get {
                return ((string)(this["RSCP_aet"]));
            }
            set {
                this["RSCP_aet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string RSCP_host {
            get {
                return ((string)(this["RSCP_host"]));
            }
            set {
                this["RSCP_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104")]
        public string RSCP_port {
            get {
                return ((string)(this["RSCP_port"]));
            }
            set {
                this["RSCP_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST_SCP")]
        public string LSCP_aet {
            get {
                return ((string)(this["LSCP_aet"]));
            }
            set {
                this["LSCP_aet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1104")]
        public string LSCP_port {
            get {
                return ((string)(this["LSCP_port"]));
            }
            set {
                this["LSCP_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LSCP_use_tls {
            get {
                return ((bool)(this["LSCP_use_tls"]));
            }
            set {
                this["LSCP_use_tls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LSCP_cert_subj {
            get {
                return ((string)(this["LSCP_cert_subj"]));
            }
            set {
                this["LSCP_cert_subj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LSCP_tumbprint {
            get {
                return ((string)(this["LSCP_tumbprint"]));
            }
            set {
                this["LSCP_tumbprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LSCP_use_cn {
            get {
                return ((bool)(this["LSCP_use_cn"]));
            }
            set {
                this["LSCP_use_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SCU_use_cn {
            get {
                return ((bool)(this["SCU_use_cn"]));
            }
            set {
                this["SCU_use_cn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LSCP_mutual_auth {
            get {
                return ((bool)(this["LSCP_mutual_auth"]));
            }
            set {
                this["LSCP_mutual_auth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LSCP_accepted {
            get {
                return ((string)(this["LSCP_accepted"]));
            }
            set {
                this["LSCP_accepted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCU_cert_store {
            get {
                return ((int)(this["SCU_cert_store"]));
            }
            set {
                this["SCU_cert_store"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCU_method {
            get {
                return ((int)(this["SCU_method"]));
            }
            set {
                this["SCU_method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LSCP_cert_store {
            get {
                return ((int)(this["LSCP_cert_store"]));
            }
            set {
                this["LSCP_cert_store"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LSCP_method {
            get {
                return ((int)(this["LSCP_method"]));
            }
            set {
                this["LSCP_method"] = value;
            }
        }
    }
}
